CREATE TABLE artillary(
   artillery_id INTEGER  NOT NULL PRIMARY KEY 
  ,range        INTEGER  NOT NULL
  ,clip_size    INTEGER  NOT NULL
  ,weapon       VARCHAR(22) NOT NULL
  ,posting      VARCHAR(19) NOT NULL
);
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (579,20,19,'AMD65.00','Ahmedabad');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (453,25,13,'M9 Pistol','Rajkot');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (286,30,33,'AN-94','Junagadh');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (593,35,90,'Model 1910','Morbi');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (507,40,72,'M9 Pistol','Porbandar');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (222,45,65,'AR-11','Bangalore');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (258,50,43,'FN MAG','Hyderabad');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (358,55,50,'M82 Barrett rifle','Pune');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (444,60,88,'MG3','Surat');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (252,65,13,'Dragunov SVD','Kanpur');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (331,70,8,'A-91','Jaipur');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (245,75,68,'AMP-68','Nagpur');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (224,80,37,'Colt M1900','Patna');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (444,85,26,'Ak 5','Lucknow');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (262,90,40,'L96A1','Indore');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (425,95,69,'MG3','Vadodara');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (464,100,36,'MG3','Bhopal');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (285,105,69,'Heckler & Koch USP','Coimbatore');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (465,110,29,'AR-16','Ludhiana');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (358,115,10,'Bren light machine gun','Kochi');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (219,120,15,'RPD','Vishakhapatnam');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (293,125,56,'AR-16','Agra');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (356,130,54,'Ak 5','Varanasi');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (585,135,99,'FN MAG','Madurai');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (473,140,41,'Steyr M Series','Merut');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (529,145,45,'FN SCAR','Nashik');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (546,150,75,'Beretta 8000','Jabalpur');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (325,155,86,'AN-94','Jamshedpur');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (451,160,67,'AMP-68','Asansol');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (574,165,23,'M21 rifle','Dhanbad');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (388,170,93,'AN-94','Faridabad');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (218,175,16,'Jericho 941','Allahabad');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (460,180,43,'Colt M1900','Amritsar');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (248,185,84,'MG3','Vijaywada');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (478,190,64,'Model 1907 Military','Lluka Eperme');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (453,195,89,'Model 1907 Military','Tayu');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (388,200,23,'L96A1','Shuigou');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (304,205,48,'DPM','Banjar Batuaji Kaja');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (402,210,46,'XM29 OICW','Chikan');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (396,215,45,'M4 Carbine','Igcocolo');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (528,220,67,'MG3','Xihuachi');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (404,225,15,'AAI ACR','Boawae');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (486,230,36,'Colt Model 1903','Kyrylivka');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (577,235,57,'A-91','Villa Serrano');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (532,240,78,'M9 Pistol','Manacsac');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (475,245,6,'AMD65.00','San Sebastian');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (239,250,61,'AN-94','Skole');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (272,255,39,'Model 1907 Military','Cinyumput');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (556,260,83,'Desert Eagle','Suchy');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (439,265,14,'RPG-7','Bulihan');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (584,270,41,'L96A1','Tangul Wetan');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (344,275,62,'Walther P38','Dingshan');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (242,280,8,'Arsenal SLR-95','Stamford');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (404,285,50,'FN SCAR','El Mirador');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (543,290,10,'Beretta 8000','Otoka');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (238,295,80,'M4 Carbine','Farrokh Shahr');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (247,300,51,'Steyr M Series','Al Mijlad');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (273,305,57,'Dragunov SVD','Snegiri');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (559,310,58,'Jericho 941','Huertas');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (298,315,97,'MG3','Linjiang');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (338,320,54,'APS Underwater Rifle','Half Way Tree');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (556,325,58,'M1911','Dasanlian Lauk');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (431,330,50,'Colt Model 1903','Kanchanaburi');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (347,335,29,'M1911','Sumberjati');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (481,340,66,'Tabuk Sniper Rifle','Dalumangcob');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (289,345,81,'FN MAG','Itacoatiara');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (400,350,58,'Model 1905 Military','Tawaramoto');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (528,355,46,'XM29 OICW','Fray Bentos');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (376,360,16,'UZI','Jarada');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (551,365,51,'A-91','Kyosai');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (224,370,75,'Model 1905 Military','Kontagora');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (240,375,77,'Colt M1900','Usarin');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (297,380,93,'AAI ACR','Dadiharja');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (256,385,28,'Pocket Hammerless','Watsa');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (310,390,14,'AAI XM70','Dawuhan');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (298,395,98,'Browning Hi-Power','Hengbanqiao');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (255,400,97,'Model 1909','Perm');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (226,405,71,'AAI XM70','Tangba');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (274,410,30,'M21 rifle','Matozinhos');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (581,415,50,'DPM','Perugia');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (599,420,65,'M1911','Nong Khai');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (317,425,69,'PK machine gun','Nantes');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (263,430,57,'Dragunov SVD','Chiba');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (341,435,10,'Browning Hi-Power','Shancheng');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (268,440,39,'Browning Hi-Power','Stockholm');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (363,445,29,'Browning Hi-Power','Al Jafr');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (211,450,47,'FN Minimi','Wielgie');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (533,455,21,'M79 grenade launcher','Kamakura');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (276,460,15,'PPK','Angers');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (399,465,61,'Heckler & Koch USP','Trelew');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (452,470,28,'Ak 5','Bairro');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (455,475,23,'Browning Hi-Power','Riangbao');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (245,480,61,'Type 67 GPMG','Angers');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (284,485,78,'AN11 TISS','Awat');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (303,490,48,'M40 rifle','Cergy-Pontoise');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (581,495,20,'AN-94','Xindong');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (461,500,15,'Pocket Hammerless','Cotonou');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (410,505,76,'MG34','Dulian');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (581,510,31,'AMP-68','Kadyy');
INSERT INTO artillary(artillery_id,range,clip_size,weapon,posting) VALUES (479,515,33,'RPG-7','Ndano');
