CREATE TABLE mytable(
   pow_id INTEGER  NOT NULL PRIMARY KEY 
  ,name   VARCHAR(20) NOT NULL
  ,place  VARCHAR(23) NOT NULL
  ,id     INTEGER  NOT NULL
);
INSERT INTO mytable(pow_id,name,place,id) VALUES (1000,'Phelan Swanson','Cermik',135);
INSERT INTO mytable(pow_id,name,place,id) VALUES (1137,'Edward Head','Sodertalje',947);
INSERT INTO mytable(pow_id,name,place,id) VALUES (1274,'Clinton Harrison','Lizge',111);
INSERT INTO mytable(pow_id,name,place,id) VALUES (1411,'Xander Mullins','Montignoso',959);
INSERT INTO mytable(pow_id,name,place,id) VALUES (1548,'Wesley Prince','Secunderabad',922);
INSERT INTO mytable(pow_id,name,place,id) VALUES (1685,'Leo Graham','Olympia',818);
INSERT INTO mytable(pow_id,name,place,id) VALUES (1822,'Igor Weeks','Tresigallo',888);
INSERT INTO mytable(pow_id,name,place,id) VALUES (1959,'Clarke Mullins','Laken',658);
INSERT INTO mytable(pow_id,name,place,id) VALUES (2096,'Melvin Gay','Baltimore',204);
INSERT INTO mytable(pow_id,name,place,id) VALUES (2233,'Edward Brown','Genzano di Lucania',837);
INSERT INTO mytable(pow_id,name,place,id) VALUES (2370,'Calvin Campbell','Kester',125);
INSERT INTO mytable(pow_id,name,place,id) VALUES (2507,'Kenyon Riggs','Traiskirchen',732);
INSERT INTO mytable(pow_id,name,place,id) VALUES (2644,'Samuel Andrews','Jauchelette',927);
INSERT INTO mytable(pow_id,name,place,id) VALUES (2781,'Jarrod Ray','Saint-Marc',999);
INSERT INTO mytable(pow_id,name,place,id) VALUES (2918,'Forrest Hill','Stamford',964);
INSERT INTO mytable(pow_id,name,place,id) VALUES (3055,'Callum Caldwell','Lacombe County',230);
INSERT INTO mytable(pow_id,name,place,id) VALUES (3192,'Abdul Mccray','Desteldonk',324);
INSERT INTO mytable(pow_id,name,place,id) VALUES (3329,'Carlos Mack','Pretoro',129);
INSERT INTO mytable(pow_id,name,place,id) VALUES (3466,'Vaughan Petty','Cincinnati',472);
INSERT INTO mytable(pow_id,name,place,id) VALUES (3603,'Allistair Byrd','Ham-sur-Sambre',771);
INSERT INTO mytable(pow_id,name,place,id) VALUES (3740,'Yardley Calderon','Perpignan',872);
INSERT INTO mytable(pow_id,name,place,id) VALUES (3877,'Rahim Shaffer','Tiruvarur',989);
INSERT INTO mytable(pow_id,name,place,id) VALUES (4014,'George Schwartz','Launceston',863);
INSERT INTO mytable(pow_id,name,place,id) VALUES (4151,'Nash Stanley','Colorno',144);
INSERT INTO mytable(pow_id,name,place,id) VALUES (4288,'Steel Dominguez','Schagen',119);
INSERT INTO mytable(pow_id,name,place,id) VALUES (4425,'Phillip Figueroa','Bernau',896);
INSERT INTO mytable(pow_id,name,place,id) VALUES (4562,'Francis Wheeler','Cauquenes',736);
INSERT INTO mytable(pow_id,name,place,id) VALUES (4699,'Abel Morton','Stratford',161);
INSERT INTO mytable(pow_id,name,place,id) VALUES (4836,'Leonard Atkins','Gelsenkirchen',610);
INSERT INTO mytable(pow_id,name,place,id) VALUES (4973,'Sylvester Mullen','Santa Maria',292);
INSERT INTO mytable(pow_id,name,place,id) VALUES (5110,'Melvin Mccormick','Kurnool',634);
INSERT INTO mytable(pow_id,name,place,id) VALUES (5247,'Caesar Frye','Meer',737);
INSERT INTO mytable(pow_id,name,place,id) VALUES (5384,'Damon Guzman','100 Mile House',269);
INSERT INTO mytable(pow_id,name,place,id) VALUES (5521,'Aladdin Mclaughlin','Pichilemu',944);
INSERT INTO mytable(pow_id,name,place,id) VALUES (5658,'Eaton Goff','Dalbeattie',907);
INSERT INTO mytable(pow_id,name,place,id) VALUES (5795,'Raja Rivas','Avadi',169);
INSERT INTO mytable(pow_id,name,place,id) VALUES (5932,'Cadman Stanton','Wenduine',322);
INSERT INTO mytable(pow_id,name,place,id) VALUES (6069,'Lamar Ramos','Goksun',906);
INSERT INTO mytable(pow_id,name,place,id) VALUES (6206,'Keith Harvey','Krakow',484);
INSERT INTO mytable(pow_id,name,place,id) VALUES (6343,'Clinton Cotton','San Jose de Maipo',858);
INSERT INTO mytable(pow_id,name,place,id) VALUES (6480,'Kevin Ortiz','Didim',340);
INSERT INTO mytable(pow_id,name,place,id) VALUES (6617,'Jonas Duran','Ludvika',821);
INSERT INTO mytable(pow_id,name,place,id) VALUES (6754,'Sean Alvarez','Begles',716);
INSERT INTO mytable(pow_id,name,place,id) VALUES (6891,'Benedict Conner','Aserra',337);
INSERT INTO mytable(pow_id,name,place,id) VALUES (7028,'Roth Hoffman','Hastings',593);
INSERT INTO mytable(pow_id,name,place,id) VALUES (7165,'Samson Stevenson','Siculiana',879);
INSERT INTO mytable(pow_id,name,place,id) VALUES (7302,'Hayden Lawrence','Calgary',411);
INSERT INTO mytable(pow_id,name,place,id) VALUES (7439,'Abel Watson','Jodhpur',134);
INSERT INTO mytable(pow_id,name,place,id) VALUES (7576,'Blake Gentry','Mumbai',179);
INSERT INTO mytable(pow_id,name,place,id) VALUES (7713,'Rashad Valentine','Horsham',441);
INSERT INTO mytable(pow_id,name,place,id) VALUES (7850,'Mohammad Kaufman','Blairgowrie',374);
INSERT INTO mytable(pow_id,name,place,id) VALUES (7987,'Colby Charles','Hasselt',662);
INSERT INTO mytable(pow_id,name,place,id) VALUES (8124,'Levi Olson','Saint John',351);
INSERT INTO mytable(pow_id,name,place,id) VALUES (8261,'Lamar Holder','Cuceglio',664);
INSERT INTO mytable(pow_id,name,place,id) VALUES (8398,'Vincent Henderson','Elsene',978);
INSERT INTO mytable(pow_id,name,place,id) VALUES (8535,'Travis Nguyen','Noicattaro',841);
INSERT INTO mytable(pow_id,name,place,id) VALUES (8672,'Kevin Watts','Morwell',293);
INSERT INTO mytable(pow_id,name,place,id) VALUES (8809,'Tanek Horne','Howrah',889);
INSERT INTO mytable(pow_id,name,place,id) VALUES (8946,'Seth Rich','Cabrero',199);
INSERT INTO mytable(pow_id,name,place,id) VALUES (9083,'Hiram Kidd','Harelbeke',283);
INSERT INTO mytable(pow_id,name,place,id) VALUES (9220,'Ira Dodson','San Gregorio nelle Alpi',327);
INSERT INTO mytable(pow_id,name,place,id) VALUES (9357,'Baker Hahn','North Battleford',839);
INSERT INTO mytable(pow_id,name,place,id) VALUES (9494,'Hayes Ball','Lakeshore',121);
INSERT INTO mytable(pow_id,name,place,id) VALUES (9631,'Allistair Cooper','Cuccaro Vetere',700);
INSERT INTO mytable(pow_id,name,place,id) VALUES (9768,'Orson Hooper','Ramsey',591);
INSERT INTO mytable(pow_id,name,place,id) VALUES (9905,'Kyle Frye','Vilna',893);
INSERT INTO mytable(pow_id,name,place,id) VALUES (1042,'Christopher Mcmillan','Wick',372);
INSERT INTO mytable(pow_id,name,place,id) VALUES (1179,'August Hanson','Dollard-des-Ormeaux',865);
INSERT INTO mytable(pow_id,name,place,id) VALUES (1316,'August Mckay','Fraserburgh',498);
