CREATE TABLE mytable(
   terrorist    VARCHAR(21) NOT NULL 
  ,alias        VARCHAR(21) NOT NULL PRIMARY KEY
  ,organization VARCHAR(62) NOT NULL
);
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Samuel R. Livingston','Olivia W. Sanford','Harakat al-Shuhada''a al-Islamiyah');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Moana U. Kemp','Ulysses S. Hurst','Front for the Liberation of the French Somali Coast');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Randall S. Velez','Kareem P. Kent','Territorial Anti-Imperialist Nuclei');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Shad B. Hatfield','Hamilton L. Ayala','Charles Martel Group');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Neil C. Flynn','Kaye M. Stokes','Turkish Islamic Jihad');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Kane T. Ratliff','Prescott B. Marquez','Ethiopian People''s Revolutionary Army');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Jerry N. Valentine','Claire Y. Dickson','al-Fatah Uprising');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Jason T. Robbins','Jesse C. Alvarez','VAR-Palmares');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Colby I. Hall','Berk U. Mcneil','Arab Fedayeen Cells');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Wade Q. Reid','Laith Q. Mccall','Cinchonero Movimiento Popular de Liberaci�n (MPL)');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Dalton O. Bruce','Raya H. Franco','Arab Struggle Movement for the Liberation of Ahvaz');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Josephine J. Callahan','Rigel X. Burt','Shurafa al-Urdun');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Jael G. Whitfield','Hadassah E. Sellers','January 31 Popular Front');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Aidan D. Hendrix','Roanna R. Gordon','Clandestini Corsi');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Yoko R. Floyd','Mallory T. Hampton','Turkish People''s Liberation Front (TPLF) (THKP-C)');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Nyssa E. Garcia','Veronica J. Lester','New Red Brigades/Communist Combatant Party');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Jesse N. Cox','Glenna W. Moses','Armed Revolutionary Left');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Ronan G. Bright','Blythe D. Fulton','Canary Islands Independence Movement');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Vance X. Levy','Amaya M. Campos','Saif-ul-Muslimeen');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Pearl E. Sloan','Dieter B. Douglas','Kuki Liberation Army (KLA)');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Melissa J. Cohen','Brenda U. Glover','Zomi Revolutionary Army (ZRA)');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Florence F. Ballard','Brandon K. Blevins','Lebanese Liberation Front');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Slade M. Ruiz','Morgan P. Spears','Mujahideen Division Khandaq');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Jameson G. Bruce','Uta H. Oconnor','Revolutionary Offensive Cells');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Barclay D. Espinoza','Curran M. Hess','al-Intiqami al-Pakistani');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Yardley U. Tanner','Abbot J. Ellison','Nationalist Kurdish Revenge Teams');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Lacy B. Church','Darryl N. Conley','Bagramyan Battalion');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Shannon X. Horn','Tatyana W. Wallace','Group of Popular Combatants (GPC)');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Steel R. Dominguez','Faith S. Nieves','Resistenza Corsa');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Danielle J. Davidson','Teagan P. Cook','Third of October Group');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Hyatt Z. Workman','Lacey J. Slater','People''s Vanguard Organization');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Rinah O. Avery','Salvador L. Hubbard','Birsa Commando Force (BCF)');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Myles N. Tucker','Avye B. Anderson','United Kuki Liberation Front (UKLF)');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Keiko U. Pearson','Anika R. Burks','Black Revolutionary Assault Team');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Kelly Y. Baker','Leandra B. Sampson','New Armenian Resistance (NAR)');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Fulton J. Snider','Alec U. Walker','Jamatul Mujahedin Bangladesh');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Warren C. Workman','Catherine O. Rich','Underground Government of the Free Democratic People of Laos');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Tanya E. Finch','Ferdinand C. Booth','Lashkar-I-Omar');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Veda F. Mccoy','Vance E. Rowe','al-Mansoorain');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Claire J. Bentley','Isadora M. Carpenter','South Londonderry Volunteers (SLV)');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Mercedes E. Castro','Alexis J. Rosario','al-Umar Mujahideen');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Nathaniel G. Lindsay','Zachary G. Burris','Hector Riobe Brigade');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Ima F. Decker','Todd S. Sweeney','Islamic Defense Force');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Ian M. Navarro','Justina P. Hood','Liberation Front of Quebec');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Joy L. Short','Sonia I. Harrell','Peronist Armed Forces');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Colin M. Shannon','Mason A. Singleton','Lautaro Youth Movement');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Regina D. Frederick','Reece Z. Schwartz','EPA (Ejercito del Pueblo en Armas)');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Jade P. Jenkins','Marvin M. Shannon','United Self-Defense Forces of Venezuela (AUV)');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Lawrence G. Bradshaw','Jordan F. Smith','Guevarista Revolutionary Army (ERG)');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Grace H. Huffman','Victoria V. Wilson','Battalion of the Martyr Abdullah Azzam');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Halla T. Sutton','Rhiannon Y. Mcclain','Lebanese Arab Youth');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Yeo K. Clements','Bernard I. Walton','Guadeloupe Liberation Army');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Sigourney I. Moore','Simone D. Christensen','Uganda Democratic Christian Army (UDCA)');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Nolan O. Baxter','Kasper G. Hopkins','Islamic Action in Iraq');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Jolie O. Rhodes','Marvin E. Bradley','February 28 Popular Leagues');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Kelly D. Harper','Hasad I. Santos','Mujahideen KOMPAK');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Micah R. Barr','Jescie Q. Combs','Andres Castro United Front (FUAC)');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Bell O. Price','Palmer Q. Lee','Islamic Front for the Liberation of Palestine (IFLP)');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Seth H. Brown','Wynne Q. Wilcox','Spanish Basque Battalion');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Avye S. Vega','Cruz H. Rice','Arab Nationalist Youth for the Liberation of Palestine (ANYLP)');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Phillip D. Rush','Angelica F. Solis','Popular Self-Defense Forces (FAP)');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Idola Y. Wyatt','Justin G. Patel','Jaish-ul-Muslimin');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Brennan E. Sutton','Lucius O. Williams','Arab Communist Organization');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Akeem R. Lynn','Preston J. Mcdowell','People''s Liberation Forces (Colombia)');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Oliver R. Stuart','Aquila W. Craft','Islamic Renewal Movement');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Rashad K. Dickson','Jesse N. Ray','National Revolutionary Command (Omar al-Mukhtar)');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Neville X. Combs','Jakeem S. Perry','TKEP/L');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Clio J. Walls','Hyacinth T. Albert','People''s Revolutionary Militias');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Quincy J. Beck','Marny U. Alexander','Yemen Islamic Jihad');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Nolan V. Stanley','Pamela A. Robles','al-Gama''a al-Islamiyya (GAI)');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Ali R. Mcdonald','Alexandra L. Bridges','Turkish People''s Liberation Army (TPLA)');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Abraham H. Bernard','Penelope B. Keller','Riyad us-Saliheyn Martyrs'' Brigade');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Alexander B. Bird','Clio Y. Cole','United Nasserite Organization');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Nina C. Doyle','Berk G. Kelley','al-Ittihaad al-Islami (AIAI)');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Joseph T. Greene','Ocean L. Silva','December 20 Movement');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Jakeem M. Ford','Tate I. Hamilton','Strugglers for the Unity and Freedom of Greater Syria');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Nigel M. Byrd','Prescott P. Sampson','Internet Black Tigers');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Iliana U. Garrison','Anne H. Reeves','Revolutionary Front for Proletarian Action');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Selma X. Petersen','Porter G. Raymond','Jaime Bateman Cayon Group (JBC)');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Sybil F. Macdonald','Branden R. Key','New Revolutionary Alternative');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Gregory P. Salas','Alden U. Powers','Che Guevara Brigade');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Kay C. Mays','Ralph L. Ayala','Harakat ul-Jihad-i-Islami/Bangladesh (HUJI-B)');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Hedy B. Oneal','Quail Y. Frye','Tunisian Combatant Group (TCG)');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Ali F. Woodard','Baxter C. Burton','Jenin Martyr''s Brigade');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Jason G. Petty','Nathan I. Brock','Anti-Imperialist Cell (AIZ)');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Nero E. Avery','Eagan J. Walls','Islami Inqilabi Mahaz');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Jael L. Benson','Cora G. Huff','Popular Revolutionary Vanguard');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Hilary G. Rice','Molly R. Hart','Armenian Revolutionary Army');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Daquan I. Ryan','Melinda G. Dean','Revolutionary Worker Clandestine Union of the People Party');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Troy Q. Cobb','Rhea H. Galloway','Iraqi Liberation Army');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Allen R. Suarez','Aurelia O. Morton','Zimbabwe African Nationalist Union (ZANU)');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Herman I. Dixon','Tana B. Hardy','Movement for Democracy and Development (MDD)');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Zachery H. Witt','Marah R. Brewer','United People''s Democratic Solidarity (UPDS)');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Camille O. Rocha','Myles Q. Barr','Armed Revolutionary Action');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Idola B. Pitts','Bo T. Hubbard','Carapaica Revolutionary Movement');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Jacqueline Y. Hyde','Denise W. Gentry','Sami al-Ghul Brigades');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Desirae N. Horton','Halee A. Burke','Kurdistan Freedom Hawks');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Shafira B. Cobb','Ashely C. Barker','Ummah Liberation Army');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Reuben M. Holt','Scott V. Bolton','People''s United Liberation Front (PULF)');
INSERT INTO mytable(terrorist,alias,organization) VALUES ('Peter P. Stein','Dominique U. Haley','al-Nawaz');
