CREATE TABLE mytable(
   base         VARCHAR(56) NOT NULL PRIMARY KEY
  ,organization VARCHAR(62) NOT NULL
);
INSERT INTO mytable(base,organization) VALUES ('Libya','Harakat al-Shuhada''a al-Islamiyah');
INSERT INTO mytable(base,organization) VALUES ('Djibouti, Somalia','Front for the Liberation of the French Somali Coast');
INSERT INTO mytable(base,organization) VALUES ('Italy','Territorial Anti-Imperialist Nuclei');
INSERT INTO mytable(base,organization) VALUES ('France','Charles Martel Group');
INSERT INTO mytable(base,organization) VALUES ('Turkey','Turkish Islamic Jihad');
INSERT INTO mytable(base,organization) VALUES ('Ethiopia, Sudan','Ethiopian People''s Revolutionary Army');
INSERT INTO mytable(base,organization) VALUES ('Jordan, Lebanon, Syria, West Bank/Gaza','al-Fatah Uprising');
INSERT INTO mytable(base,organization) VALUES ('Brazil, Uruguay','VAR-Palmares');
INSERT INTO mytable(base,organization) VALUES ('Lebanon','Arab Fedayeen Cells');
INSERT INTO mytable(base,organization) VALUES ('Honduras, Nicaragua','Cinchonero Movimiento Popular de Liberaci�n (MPL)');
INSERT INTO mytable(base,organization) VALUES ('Iran','Arab Struggle Movement for the Liberation of Ahvaz');
INSERT INTO mytable(base,organization) VALUES ('Jordan','Shurafa al-Urdun');
INSERT INTO mytable(base,organization) VALUES ('Guatemala','January 31 Popular Front');
INSERT INTO mytable(base,organization) VALUES ('Corsica, France','Clandestini Corsi');
INSERT INTO mytable(base,organization) VALUES ('Turkey','Turkish People''s Liberation Front (TPLF) (THKP-C)');
INSERT INTO mytable(base,organization) VALUES ('Italy','New Red Brigades/Communist Combatant Party');
INSERT INTO mytable(base,organization) VALUES ('Ecuador','Armed Revolutionary Left');
INSERT INTO mytable(base,organization) VALUES ('Algeria, Spain','Canary Islands Independence Movement');
INSERT INTO mytable(base,organization) VALUES ('Afghanistan','Saif-ul-Muslimeen');
INSERT INTO mytable(base,organization) VALUES ('India','Kuki Liberation Army (KLA)');
INSERT INTO mytable(base,organization) VALUES ('India','Zomi Revolutionary Army (ZRA)');
INSERT INTO mytable(base,organization) VALUES ('Lebanon','Lebanese Liberation Front');
INSERT INTO mytable(base,organization) VALUES ('Indonesia, Malaysia','Mujahideen Division Khandaq');
INSERT INTO mytable(base,organization) VALUES ('Italy','Revolutionary Offensive Cells');
INSERT INTO mytable(base,organization) VALUES ('n/a','al-Intiqami al-Pakistani');
INSERT INTO mytable(base,organization) VALUES ('Turkey','Nationalist Kurdish Revenge Teams');
INSERT INTO mytable(base,organization) VALUES ('Georgia','Bagramyan Battalion');
INSERT INTO mytable(base,organization) VALUES ('Ecuador','Group of Popular Combatants (GPC)');
INSERT INTO mytable(base,organization) VALUES ('Corsica, France','Resistenza Corsa');
INSERT INTO mytable(base,organization) VALUES ('France, Switzerland','Third of October Group');
INSERT INTO mytable(base,organization) VALUES ('Costa Rica','People''s Vanguard Organization');
INSERT INTO mytable(base,organization) VALUES ('India','Birsa Commando Force (BCF)');
INSERT INTO mytable(base,organization) VALUES ('India','United Kuki Liberation Front (UKLF)');
INSERT INTO mytable(base,organization) VALUES ('United States','Black Revolutionary Assault Team');
INSERT INTO mytable(base,organization) VALUES ('Belgium, France, Italy, United Kingdom','New Armenian Resistance (NAR)');
INSERT INTO mytable(base,organization) VALUES ('Bangladesh','Jamatul Mujahedin Bangladesh');
INSERT INTO mytable(base,organization) VALUES ('Laos','Underground Government of the Free Democratic People of Laos');
INSERT INTO mytable(base,organization) VALUES ('Pakistan','Lashkar-I-Omar');
INSERT INTO mytable(base,organization) VALUES ('India, Kashmir, Pakistan','al-Mansoorain');
INSERT INTO mytable(base,organization) VALUES ('Northern Ireland (UK), United Kingdom','South Londonderry Volunteers (SLV)');
INSERT INTO mytable(base,organization) VALUES ('Pakistan','al-Umar Mujahideen');
INSERT INTO mytable(base,organization) VALUES ('Haiti, United States','Hector Riobe Brigade');
INSERT INTO mytable(base,organization) VALUES ('India','Islamic Defense Force');
INSERT INTO mytable(base,organization) VALUES ('Canada','Liberation Front of Quebec');
INSERT INTO mytable(base,organization) VALUES ('Argentina','Peronist Armed Forces');
INSERT INTO mytable(base,organization) VALUES ('chile','Lautaro Youth Movement');
INSERT INTO mytable(base,organization) VALUES ('Venezuela','EPA (Ejercito del Pueblo en Armas)');
INSERT INTO mytable(base,organization) VALUES ('Venezuela','United Self-Defense Forces of Venezuela (AUV)');
INSERT INTO mytable(base,organization) VALUES ('Colombia','Guevarista Revolutionary Army (ERG)');
INSERT INTO mytable(base,organization) VALUES ('Egypt, Jordan, Syria','Battalion of the Martyr Abdullah Azzam');
INSERT INTO mytable(base,organization) VALUES ('Lebanon','Lebanese Arab Youth');
INSERT INTO mytable(base,organization) VALUES ('Guadeloupe','Guadeloupe Liberation Army');
INSERT INTO mytable(base,organization) VALUES ('Sudan, Uganda','Uganda Democratic Christian Army (UDCA)');
INSERT INTO mytable(base,organization) VALUES ('Iran, Iraq','Islamic Action in Iraq');
INSERT INTO mytable(base,organization) VALUES ('El Salvador','February 28 Popular Leagues');
INSERT INTO mytable(base,organization) VALUES ('Indonesia','Mujahideen KOMPAK');
INSERT INTO mytable(base,organization) VALUES ('Nicaragua','Andres Castro United Front (FUAC)');
INSERT INTO mytable(base,organization) VALUES ('Lebanon','Islamic Front for the Liberation of Palestine (IFLP)');
INSERT INTO mytable(base,organization) VALUES ('France, Spain','Spanish Basque Battalion');
INSERT INTO mytable(base,organization) VALUES ('Libya','Arab Nationalist Youth for the Liberation of Palestine (ANYLP)');
INSERT INTO mytable(base,organization) VALUES ('Democratic Republic of the Congo','Popular Self-Defense Forces (FAP)');
INSERT INTO mytable(base,organization) VALUES ('Afghanistan','Jaish-ul-Muslimin');
INSERT INTO mytable(base,organization) VALUES ('Lebanon, Syria','Arab Communist Organization');
INSERT INTO mytable(base,organization) VALUES ('Colombia','People''s Liberation Forces (Colombia)');
INSERT INTO mytable(base,organization) VALUES ('Jordan','Islamic Renewal Movement');
INSERT INTO mytable(base,organization) VALUES ('Lebanon','National Revolutionary Command (Omar al-Mukhtar)');
INSERT INTO mytable(base,organization) VALUES ('Turkey','TKEP/L');
INSERT INTO mytable(base,organization) VALUES ('Ecuador','People''s Revolutionary Militias');
INSERT INTO mytable(base,organization) VALUES ('Afghanistan, Libya, United Kingdom, United States, Yemen','Yemen Islamic Jihad');
INSERT INTO mytable(base,organization) VALUES ('Afghanistan, Egypt','al-Gama''a al-Islamiyya (GAI)');
INSERT INTO mytable(base,organization) VALUES ('Turkey','Turkish People''s Liberation Army (TPLA)');
INSERT INTO mytable(base,organization) VALUES ('Chechnya, Russia','Riyad us-Saliheyn Martyrs'' Brigade');
INSERT INTO mytable(base,organization) VALUES ('Cyprus, Lebanon','United Nasserite Organization');
INSERT INTO mytable(base,organization) VALUES ('Ethiopia, Kenya, Somalia','al-Ittihaad al-Islami (AIAI)');
INSERT INTO mytable(base,organization) VALUES ('Panama','December 20 Movement');
INSERT INTO mytable(base,organization) VALUES ('Lebanon','Strugglers for the Unity and Freedom of Greater Syria');
INSERT INTO mytable(base,organization) VALUES ('Sri Lanka','Internet Black Tigers');
INSERT INTO mytable(base,organization) VALUES ('Belgium','Revolutionary Front for Proletarian Action');
INSERT INTO mytable(base,organization) VALUES ('Colombia','Jaime Bateman Cayon Group (JBC)');
INSERT INTO mytable(base,organization) VALUES ('Russia','New Revolutionary Alternative');
INSERT INTO mytable(base,organization) VALUES ('Argentina','Che Guevara Brigade');
INSERT INTO mytable(base,organization) VALUES ('Bangladesh','Harakat ul-Jihad-i-Islami/Bangladesh (HUJI-B)');
INSERT INTO mytable(base,organization) VALUES ('Afghanistan','Tunisian Combatant Group (TCG)');
INSERT INTO mytable(base,organization) VALUES ('Israel, West Bank/Gaza','Jenin Martyr''s Brigade');
INSERT INTO mytable(base,organization) VALUES ('Germany','Anti-Imperialist Cell (AIZ)');
INSERT INTO mytable(base,organization) VALUES ('India, Kashmir, Pakistan','Islami Inqilabi Mahaz');
INSERT INTO mytable(base,organization) VALUES ('Brazil','Popular Revolutionary Vanguard');
INSERT INTO mytable(base,organization) VALUES ('United States','Armenian Revolutionary Army');
INSERT INTO mytable(base,organization) VALUES ('Mexico','Revolutionary Worker Clandestine Union of the People Party');
INSERT INTO mytable(base,organization) VALUES ('Iraq, Lebanon, Turkey','Iraqi Liberation Army');
INSERT INTO mytable(base,organization) VALUES ('Mozambique, Rhodesia, Zimbabwe','Zimbabwe African Nationalist Union (ZANU)');
INSERT INTO mytable(base,organization) VALUES ('Cameroon, Chad, Libya, Nigeria','Movement for Democracy and Development (MDD)');
INSERT INTO mytable(base,organization) VALUES ('India','United People''s Democratic Solidarity (UPDS)');
INSERT INTO mytable(base,organization) VALUES ('Mozambique, Portugal','Armed Revolutionary Action');
INSERT INTO mytable(base,organization) VALUES ('Venezuela','Carapaica Revolutionary Movement');
INSERT INTO mytable(base,organization) VALUES ('Israel, West Bank/Gaza','Sami al-Ghul Brigades');
INSERT INTO mytable(base,organization) VALUES ('Iraq, Turkey','Kurdistan Freedom Hawks');
INSERT INTO mytable(base,organization) VALUES ('Sudan','Ummah Liberation Army');
INSERT INTO mytable(base,organization) VALUES ('India','People''s United Liberation Front (PULF)');
INSERT INTO mytable(base,organization) VALUES ('Pakistan','al-Nawaz');
