CREATE TABLE IF NOT EXISTS pow (
    `pow_id` INT,
    `name` VARCHAR(20) CHARACTER SET utf8,
    `place` VARCHAR(23) CHARACTER SET utf8,
    `name` VARCHAR(21) CHARACTER SET utf8
);
INSERT INTO pow VALUES
    (44566,'Phelan Swanson','Çermik','Stuart N. Mccarty'),
    (44567,'Edward Head','Södertälje','Hedwig P. Summers'),
    (44568,'Clinton Harrison','Lige','Anjolie V. Avila'),
    (44569,'Xander Mullins','Montignoso','Joelle D. Wright'),
    (44570,'Wesley Prince','Secunderabad','Ignacia R. Cleveland'),
    (44571,'Leo Graham','Olympia','Genevieve Q. Knapp'),
    (44572,'Igor Weeks','Tresigallo','Dolan Y. Whitfield'),
    (44573,'Clarke Mullins','Laken','Lucian E. Maldonado'),
    (44574,'Melvin Gay','Baltimore','Shelby O. Hernandez'),
    (44575,'Edward Brown','Genzano di Lucania','Porter H. Henry'),
    (44576,'Calvin Campbell','Kester','Jasmine W. Wooten'),
    (44577,'Kenyon Riggs','Traiskirchen','Ross B. Hubbard'),
    (44578,'Samuel Andrews','Jauchelette','Blaze O. Schwartz'),
    (44579,'Jarrod Ray','Saint-Marc','Wynter E. Mccarthy'),
    (44580,'Forrest Hill','Stamford','Valentine X. Floyd'),
    (44581,'Callum Caldwell','Lacombe County','Gareth M. Cantu'),
    (44582,'Abdul Mccray','Desteldonk','Helen H. Lott'),
    (44583,'Carlos Mack','Pretoro','Dylan C. Hubbard'),
    (44584,'Vaughan Petty','Cincinnati','Hashim A. Joseph'),
    (44585,'Allistair Byrd','Ham-sur-Sambre','Matthew B. Salinas'),
    (44586,'Yardley Calderon','Perpignan','Ciaran K. Beck'),
    (44587,'Rahim Shaffer','Tiruvarur','Patrick O. William'),
    (44588,'George Schwartz','Launceston','Xander J. Humphrey'),
    (44589,'Nash Stanley','Colorno','Duncan F. Bond'),
    (44590,'Steel Dominguez','Schagen','Germane Y. Jacobson'),
    (44591,'Phillip Figueroa','Bernau','Xyla D. Tran'),
    (44592,'Francis Wheeler','Cauquenes','Nichole I. Macias'),
    (44593,'Abel Morton','Stratford','Florence D. Lamb'),
    (44594,'Leonard Atkins','Gelsenkirchen','Bethany N. Rogers'),
    (44595,'Sylvester Mullen','Santa Maria','Cleo U. Fields'),
    (44596,'Melvin Mccormick','Kurnool','Aquila E. Jenkins'),
    (44597,'Caesar Frye','Meer','Zahir H. Boyd'),
    (44598,'Damon Guzman','100 Mile House','Reese D. Arnold'),
    (44599,'Aladdin Mclaughlin','Pichilemu','Salvador Z. Roman'),
    (44600,'Eaton Goff','Dalbeattie','Keegan Y. Wright'),
    (44601,'Raja Rivas','Avadi','Ryan L. Crosby'),
    (44602,'Cadman Stanton','Wenduine','Diana K. Silva'),
    (44603,'Lamar Ramos','Göksun','Judith P. Harrell'),
    (44604,'Keith Harvey','Kraków','Summer S. Bean'),
    (44605,'Clinton Cotton','San José de Maipo','Lee V. Bartlett'),
    (44606,'Kevin Ortiz','Didim','Tamara Z. Golden'),
    (44607,'Jonas Duran','Ludvika','Drew C. Gibbs'),
    (44608,'Sean Alvarez','Bègles','Daniel A. Henry'),
    (44609,'Benedict Conner','Aserrí','Lamar Y. Clark'),
    (44610,'Roth Hoffman','Hastings','Mallory A. Barton'),
    (44611,'Samson Stevenson','Siculiana','Beck Z. Walters'),
    (44612,'Hayden Lawrence','Calgary','Brenden U. Hamilton'),
    (44613,'Abel Watson','Jodhpur','Arthur C. Beard'),
    (44614,'Blake Gentry','Mumbai','Chava I. Grant'),
    (44615,'Rashad Valentine','Horsham','Clinton K. Valenzuela'),
    (44616,'Mohammad Kaufman','Blairgowrie','Laurel N. Randolph'),
    (44617,'Colby Charles','Hasselt','Wilma O. Carver'),
    (44618,'Levi Olson','Saint John','Illiana K. Lewis'),
    (44619,'Lamar Holder','Cuceglio','Sawyer M. Matthews'),
    (44620,'Vincent Henderson','Elsene','Alvin E. Delacruz'),
    (44621,'Travis Nguyen','Noicattaro','Cole W. Mayo'),
    (44622,'Kevin Watts','Morwell','Quinn Z. Gates'),
    (44623,'Tanek Horne','Howrah','Blaine R. Thomas'),
    (44624,'Seth Rich','Cabrero','Astra J. Ball'),
    (44625,'Hiram Kidd','Harelbeke','Janna G. Bond'),
    (44626,'Ira Dodson','San Gregorio nelle Alpi','Elliott E. Chan'),
    (44627,'Baker Hahn','North Battleford','Melanie Z. Mason'),
    (44628,'Hayes Ball','Lakeshore','Ignacia K. Shields'),
    (44629,'Allistair Cooper','Cuccaro Vetere','Nash Z. Colon'),
    (44630,'Orson Hooper','Ramsey','Lenore D. Snow'),
    (44631,'Kyle Frye','Vilna','Hyacinth O. Wong'),
    (44632,'Christopher Mcmillan','Wick','Moses L. Mcknight'),
    (44633,'August Hanson','Dollard-des-Ormeaux','Louis K. Webster'),
    (44634,'August Mckay','Fraserburgh','Uma N. Bentley');
