CREATE TABLE IF NOT EXISTS storage (
    `city` VARCHAR(21) CHARACTER SET utf8,
    `weapons` VARCHAR(24) CHARACTER SET utf8,
    `ammo` VARCHAR(33) CHARACTER SET utf8
);
INSERT INTO storage VALUES
    ('Stonehaven','Model 1907 Military','Special (RCBD)'),
    ('Macclesfield','AMD 65','Jacketed Hollow Point (JHP)'),
    ('Bienne-lez-Happart','M9 Pistol','Semi-Jacketed (SJ)'),
    ('Baie-Comeau','AN-94','Special (RCBD)'),
    ('Nijkerk','Model 1910','Wad Cutter (WC)'),
    ('Hualañé','M9 Pistol','Jacketed Hollow Point (JHP)'),
    ('Linz','AR-11','Semi-Jacketed (SJ)'),
    ('Buguma','FN MAG','Armor Piercing (AP)'),
    ('Annapolis Royal','M82 Barrett rifle','Armor Piercing (AP)'),
    ('Heerenveen','MG3','Soft Point (SP)'),
    ('Artena','Dragunov SVD','Wad Cutter (WC)'),
    ('Kallo','A-91','Wad Cutter (WC)'),
    ('San Venanzo','AMP-68','Semi Wad Cutter (SWC)'),
    ('Okotoks','Colt M1900','Soft Point (SP)'),
    ('Hornsea','Ak 5','Full Metal Jacket (FMJ)'),
    ('Scanzano Jonico','L96A1','Armor Piercing (AP)'),
    ('Tolentino','MG3','Boat Tail (BT)'),
    ('Neuss','MG3','Semi Wad Cutter (SWC)'),
    ('Montalto Uffugo','Heckler & Koch USP','Lead Round Nose (LRN)'),
    ('Nässjö','AR-16','Semi-Jacketed (SJ)'),
    ('Pocatello','Bren light machine gun','Full Metal Jacket (FMJ)'),
    ('Sommariva Perno','RPD','Special (RCBD)'),
    ('Minderhout','AR-16','Boat Tail (BT)'),
    ('Neustrelitz','Ak 5','Full Metal Jacket (FMJ)'),
    ('Abergavenny','FN MAG','Jacketed Hollow Point (JHP)'),
    ('Caccamo','Steyr M Series','Lead Round Nose (LRN)'),
    ('Louvain-la-Neuve','FN SCAR','Soft Point (SP)'),
    ('Vicuña','Beretta 8000','Semi-Jacketed (SJ)'),
    ('Bridlington','AN-94','Semi Wad Cutter (SWC)'),
    ('Potenza','AMP-68','Boat Tail Hollow Point (BTHP)'),
    ('Hines Creek','M21 rifle','Semi-Jacketed Hollow Point (SJHP)'),
    ('Laon','AN-94','Semi Wad Cutter (SWC)'),
    ('Paradise','Jericho 941','Lead Round Nose (LRN)'),
    ('Schepdaal','Colt M1900','Wad Cutter (WC)'),
    ('Sciacca','MG3','Semi-Jacketed Hollow Point (SJHP)'),
    ('Lerwick','Model 1907 Military','Special (RCBD)'),
    ('Ottawa','Model 1907 Military','Soft Point (SP)'),
    ('Pont-de-Loup','L96A1','Full Metal Jacket (FMJ)'),
    ('Dieppe','DPM','Soft Point (SP)'),
    ('Cerreto di Spoleto','XM29 OICW','Wad Cutter (WC)'),
    ('Husum','M4 Carbine','Boat Tail Hollow Point (BTHP)'),
    ('Ashoknagar-Kalyangarh','MG3','Boat Tail Hollow Point (BTHP)'),
    ('Rosires','AAI ACR','Jacketed Hollow Point (JHP)'),
    ('Castellina in Chianti','Colt Model 1903','Soft Point (SP)'),
    ('Kalgoorlie-Boulder','A-91','Lead Round Nose (LRN)'),
    ('Steyr','M9 Pistol','Semi Wad Cutter (SWC)'),
    ('Völkermarkt','AMD 65','Boat Tail (BT)'),
    ('Cimitile','AN-94','Special (RCBD)'),
    ('Kaneohe','Model 1907 Military','Wad Cutter (WC)'),
    ('Manoppello','Desert Eagle','Soft Point (SP)'),
    ('Villers-la-Bonne-Eau','RPG-7','Armor Piercing (AP)'),
    ('Wagnele','L96A1','Full Metal Jacket (FMJ)'),
    ('Rattray','Walther P38','Wad Cutter (WC)'),
    ('Montemesola','Arsenal SLR-95','Lead Round Nose (LRN)'),
    ('Nossegem','FN SCAR','Boat Tail Hollow Point (BTHP)'),
    ('Sibret','Beretta 8000','Lead Round Nose (LRN)'),
    ('Lüneburg','M4 Carbine','Semi-Jacketed (SJ)'),
    ('Brusson','Steyr M Series','Armor Piercing (AP)'),
    ('Denny','Dragunov SVD','Semi-Jacketed (SJ)'),
    ('Pero','Jericho 941','Wad Cutter (WC)'),
    ('Aalen','MG3','Soft Point (SP)'),
    ('Ciudad Real','APS Underwater Rifle','Special (RCBD)'),
    ('Arlon','M1911','Boat Tail Hollow Point (BTHP)'),
    ('Giove','Colt Model 1903','Boat Tail Hollow Point (BTHP)'),
    ('Wilskerke','M1911','Semi-Jacketed Hollow Point (SJHP)'),
    ('Cáceres','Tabuk Sniper Rifle','Armor Piercing (AP)'),
    ('Fourbechies','FN MAG','Semi-Jacketed (SJ)'),
    ('Osogbo','Model 1905 Military','Jacketed Hollow Point (JHP)'),
    ('Ajmer','XM29 OICW','Full Metal Jacket (FMJ)'),
    ('Secunderabad','UZI','Semi-Jacketed Hollow Point (SJHP)'),
    ('Glovertown','A-91','Semi-Jacketed Hollow Point (SJHP)'),
    ('Bossuit','Model 1905 Military','Semi Wad Cutter (SWC)'),
    ('Galway','Colt M1900','Lead Round Nose (LRN)'),
    ('Picton','AAI ACR','Soft Point (SP)'),
    ('Besançon','Pocket Hammerless','Semi Wad Cutter (SWC)'),
    ('São José dos Pinhais','AAI XM70','Semi-Jacketed Hollow Point (SJHP)'),
    ('Appleby','Browning Hi-Power','Armor Piercing (AP)'),
    ('Sambhal','Model 1909','Lead Round Nose (LRN)'),
    ('Purulia','AAI XM70','Soft Point (SP)'),
    ('Emarèse','M21 rifle','Wad Cutter (WC)'),
    ('Coronel','DPM','Soft Point (SP)'),
    ('Kalyan','M1911','Semi-Jacketed Hollow Point (SJHP)'),
    ('Floriffoux','PK machine gun','Soft Point (SP)'),
    ('La Hulpe','Dragunov SVD','Full Metal Jacket (FMJ)'),
    ('Ranst','Browning Hi-Power','Semi Wad Cutter (SWC)'),
    ('Grasse','Browning Hi-Power','Lead Round Nose (LRN)'),
    ('Weert','Browning Hi-Power','Jacketed Hollow Point (JHP)'),
    ('Lochristi','FN Minimi','Special (RCBD)'),
    ('Suxy','M79 grenade launcher','Special (RCBD)'),
    ('Przemy?l','PPK','Full Metal Jacket (FMJ)'),
    ('Gooik','Heckler & Koch USP','Boat Tail Hollow Point (BTHP)'),
    ('Goutroux','Ak 5','Soft Point (SP)'),
    ('Arsoli','Browning Hi-Power','Boat Tail Hollow Point (BTHP)'),
    ('Caprino Bergamasco','Type 67 GPMG','Lead Round Nose (LRN)'),
    ('Alken','AN11 TISS','Semi-Jacketed (SJ)'),
    ('Herselt','M40 rifle','Boat Tail (BT)'),
    ('Spiere','AN-94','Full Metal Jacket (FMJ)'),
    ('Poitiers','Pocket Hammerless','Semi Wad Cutter (SWC)'),
    ('Blind River','MG34','Special (RCBD)'),
    ('Salt Spring Island','AMP-68','Semi-Jacketed (SJ)'),
    (NULL,'RPG-7','Special (RCBD)'),
    (NULL,'AR-18','Semi-Jacketed (SJ)'),
    (NULL,'Model 1909','Jacketed Hollow Point (JHP)'),
    (NULL,'Colt Model 1902 Military','Armor Piercing (AP)'),
    (NULL,'UZI','Wad Cutter (WC)'),
    (NULL,'M82 Barrett rifle','Boat Tail Hollow Point (BTHP)'),
    (NULL,NULL,'Semi-Jacketed Hollow Point (SJHP)'),
    (NULL,'Heckler & Koch PSG1','Semi-Jacketed (SJ)'),
    (NULL,'Ak 4','Full Metal Jacket (FMJ)'),
    (NULL,'Daewoo K5','Wad Cutter (WC)'),
    (NULL,'AR-16','Semi Wad Cutter (SWC)'),
    (NULL,'Luger pistol','Boat Tail Hollow Point (BTHP)'),
    (NULL,'AMD 65','Soft Point (SP)'),
    (NULL,'Jericho 941','Semi-Jacketed Hollow Point (SJHP)'),
    (NULL,'A-91','Semi-Jacketed (SJ)'),
    (NULL,'MG42','Jacketed Hollow Point (JHP)'),
    (NULL,'M9 Pistol','Armor Piercing (AP)'),
    (NULL,'Colt Model 1902 Military','Soft Point (SP)'),
    (NULL,'AMD 65','Special (RCBD)'),
    (NULL,'Colt Model 1903','Semi-Jacketed (SJ)'),
    (NULL,'FN SCAR','Boat Tail Hollow Point (BTHP)'),
    (NULL,'AN11 TISS','Boat Tail Hollow Point (BTHP)'),
    (NULL,'Heckler & Koch USP','Boat Tail Hollow Point (BTHP)'),
    (NULL,'Model 1907 Military','Full Metal Jacket (FMJ)'),
    (NULL,'MG34','Semi-Jacketed (SJ)'),
    (NULL,'A-91','Full Metal Jacket (FMJ)'),
    (NULL,'AR-11','Wad Cutter (WC)'),
    (NULL,'AN-94','Lead Round Nose (LRN)'),
    (NULL,'Model 1909','Boat Tail (BT)'),
    (NULL,'PPK','Boat Tail (BT)'),
    (NULL,'MG42','Boat Tail (BT)'),
    (NULL,'SAR-21','Jacketed Hollow Point (JHP)'),
    (NULL,'Dragunov SVD','Semi-Jacketed (SJ)'),
    (NULL,'AR-16','Boat Tail (BT)'),
    (NULL,'Colt Model 1902 Military','Semi-Jacketed (SJ)'),
    (NULL,'M79 grenade launcher','Wad Cutter (WC)'),
    (NULL,'RPG-7','Soft Point (SP)'),
    (NULL,'M40 rifle','Armor Piercing (AP)'),
    (NULL,'Colt Model 1903','Special (RCBD)'),
    (NULL,'SAR-21','Special (RCBD)'),
    (NULL,'MG42','Boat Tail Hollow Point (BTHP)'),
    (NULL,'Walther P38','Full Metal Jacket (FMJ)'),
    (NULL,'AMP-68','Semi Wad Cutter (SWC)'),
    (NULL,'PPK','Soft Point (SP)'),
    (NULL,'Ak 5','Special (RCBD)');
