CREATE TABLE IF NOT EXISTS terrorist (
    `terrorist` VARCHAR(21) CHARACTER SET utf8,
    `alias` VARCHAR(21) CHARACTER SET utf8,
    `Column_3` INT,
    `organization_name` VARCHAR(41) CHARACTER SET utf8
);
INSERT INTO terrorist VALUES
    ('Samuel R. Livingston','Olivia W. Sanford',NULL,'Harakat ul-Mujahidin'),
    ('Moana U. Kemp','Ulysses S. Hurst',NULL,'Harakat ul-Mujahidin'),
    ('Randall S. Velez','Kareem P. Kent',NULL,'Abu Sayyaf Group'),
    ('Shad B. Hatfield','Hamilton L. Ayala',NULL,'Harakat ul-Mujahidin'),
    ('Neil C. Flynn','Kaye M. Stokes',NULL,'Harakat ul-Mujahidin'),
    ('Kane T. Ratliff','Prescott B. Marquez',NULL,'al-Qa''ida'),
    ('Jerry N. Valentine','Claire Y. Dickson',NULL,'Abu Sayyaf Group'),
    ('Jason T. Robbins','Jesse C. Alvarez',NULL,'Hizbul Mujahideen'),
    ('Colby I. Hall','Berk U. Mcneil',NULL,'Islamic Jihad Group'),
    ('Wade Q. Reid','Laith Q. Mccall',NULL,'Al-Qaeda Kurdish Battalions'),
    ('Dalton O. Bruce','Raya H. Franco',NULL,'Al-Qaeda Kurdish Battalions'),
    ('Josephine J. Callahan','Rigel X. Burt',NULL,'Hizbul Mujahideen'),
    ('Jael G. Whitfield','Hadassah E. Sellers',NULL,'Hizbul Mujahideen'),
    ('Aidan D. Hendrix','Roanna R. Gordon',NULL,'Harakat ul-Mujahidin'),
    ('Yoko R. Floyd','Mallory T. Hampton',NULL,'Islamic Jihad Group'),
    ('Nyssa E. Garcia','Veronica J. Lester',NULL,'Al-Qaeda Kurdish Battalions'),
    ('Jesse N. Cox','Glenna W. Moses',NULL,'Al-Qaeda Kurdish Battalions'),
    ('Ronan G. Bright','Blythe D. Fulton',NULL,'Boko Haram'),
    ('Vance X. Levy','Amaya M. Campos',NULL,'Boko Haram'),
    ('Pearl E. Sloan','Dieter B. Douglas',NULL,'Abu Sayyaf Group'),
    ('Melissa J. Cohen','Brenda U. Glover',NULL,'Hizbul Mujahideen'),
    ('Florence F. Ballard','Brandon K. Blevins',NULL,'Abu Sayyaf Group'),
    ('Slade M. Ruiz','Morgan P. Spears',NULL,'Harakat ul-Mujahidin'),
    ('Jameson G. Bruce','Uta H. Oconnor',NULL,'Lashkar-e Tayyiba (Army of the Righteous)'),
    ('Barclay D. Espinoza','Curran M. Hess',NULL,'Lashkar-e Tayyiba (Army of the Righteous)'),
    ('Yardley U. Tanner','Abbot J. Ellison',NULL,'Islamic Jihad Union'),
    ('Lacy B. Church','Darryl N. Conley',NULL,'Harakat ul-Mujahidin'),
    ('Shannon X. Horn','Tatyana W. Wallace',NULL,'Palestine Liberation Front'),
    ('Steel R. Dominguez','Faith S. Nieves',NULL,'Al-Qaeda Kurdish Battalions'),
    ('Danielle J. Davidson','Teagan P. Cook',NULL,'Lashkar-e Tayyiba (Army of the Righteous)'),
    ('Hyatt Z. Workman','Lacey J. Slater',NULL,'Al-Qaeda Kurdish Battalions'),
    ('Rinah O. Avery','Salvador L. Hubbard',NULL,'Abu Sayyaf Group'),
    ('Myles N. Tucker','Avye B. Anderson',NULL,'Harakat ul-Mujahidin'),
    ('Keiko U. Pearson','Anika R. Burks',NULL,'al-Qa''ida'),
    ('Kelly Y. Baker','Leandra B. Sampson',NULL,'Islamic Jihad Union'),
    ('Fulton J. Snider','Alec U. Walker',NULL,'Islamic Jihad Group'),
    ('Warren C. Workman','Catherine O. Rich',NULL,'Harakat ul-Mujahidin'),
    ('Tanya E. Finch','Ferdinand C. Booth',NULL,'Harakat ul-Mujahidin'),
    ('Veda F. Mccoy','Vance E. Rowe',NULL,'Boko Haram'),
    ('Claire J. Bentley','Isadora M. Carpenter',NULL,'Al-Qaeda Kurdish Battalions'),
    ('Mercedes E. Castro','Alexis J. Rosario',NULL,'Islamic Jihad Group'),
    ('Nathaniel G. Lindsay','Zachary G. Burris',NULL,'Boko Haram'),
    ('Ima F. Decker','Todd S. Sweeney',NULL,'Al-Qaeda Kurdish Battalions'),
    ('Ian M. Navarro','Justina P. Hood',NULL,'Harakat ul-Mujahidin'),
    ('Joy L. Short','Sonia I. Harrell',NULL,'Hizbul Mujahideen'),
    ('Colin M. Shannon','Mason A. Singleton',NULL,'Abu Sayyaf Group'),
    ('Regina D. Frederick','Reece Z. Schwartz',NULL,'Boko Haram'),
    ('Jade P. Jenkins','Marvin M. Shannon',NULL,'Boko Haram'),
    ('Lawrence G. Bradshaw','Jordan F. Smith',NULL,'Harakat ul-Mujahidin'),
    ('Grace H. Huffman','Victoria V. Wilson',NULL,'Boko Haram'),
    ('Halla T. Sutton','Rhiannon Y. Mcclain',NULL,'Harakat ul-Mujahidin'),
    ('Yeo K. Clements','Bernard I. Walton',NULL,'Harakat ul-Mujahidin'),
    ('Sigourney I. Moore','Simone D. Christensen',NULL,'Islamic Jihad Union'),
    ('Nolan O. Baxter','Kasper G. Hopkins',NULL,'Harakat ul-Mujahidin'),
    ('Jolie O. Rhodes','Marvin E. Bradley',NULL,'Palestine Liberation Front'),
    ('Kelly D. Harper','Hasad I. Santos',NULL,'Al-Qaeda Kurdish Battalions'),
    ('Micah R. Barr','Jescie Q. Combs',NULL,'Abu Sayyaf Group'),
    ('Bell O. Price','Palmer Q. Lee',NULL,'Harakat ul-Mujahidin'),
    ('Seth H. Brown','Wynne Q. Wilcox',NULL,'Hizbul Mujahideen'),
    ('Avye S. Vega','Cruz H. Rice',NULL,'Palestine Liberation Front'),
    ('Phillip D. Rush','Angelica F. Solis',NULL,'Harakat ul-Mujahidin'),
    ('Idola Y. Wyatt','Justin G. Patel',NULL,'Boko Haram'),
    ('Brennan E. Sutton','Lucius O. Williams',NULL,'Lashkar-e Tayyiba (Army of the Righteous)'),
    ('Akeem R. Lynn','Preston J. Mcdowell',NULL,'Harakat ul-Mujahidin'),
    ('Oliver R. Stuart','Aquila W. Craft',NULL,'Harakat ul-Mujahidin'),
    ('Rashad K. Dickson','Jesse N. Ray',NULL,'Abu Sayyaf Group'),
    ('Neville X. Combs','Jakeem S. Perry',NULL,'Islamic Jihad Group'),
    ('Clio J. Walls','Hyacinth T. Albert',NULL,'Boko Haram'),
    ('Quincy J. Beck','Marny U. Alexander',NULL,'al-Qa''ida'),
    ('Nolan V. Stanley','Pamela A. Robles',NULL,'Al-Qaeda Kurdish Battalions'),
    ('Ali R. Mcdonald','Alexandra L. Bridges',NULL,'Al-Qaeda Kurdish Battalions'),
    ('Abraham H. Bernard','Penelope B. Keller',NULL,'Boko Haram'),
    ('Alexander B. Bird','Clio Y. Cole',NULL,'Hizbul Mujahideen'),
    ('Nina C. Doyle','Berk G. Kelley',NULL,'Boko Haram'),
    ('Joseph T. Greene','Ocean L. Silva',NULL,'Palestine Liberation Front'),
    ('Jakeem M. Ford','Tate I. Hamilton',NULL,'Islamic Jihad Group'),
    ('Nigel M. Byrd','Prescott P. Sampson',NULL,'Harakat ul-Mujahidin'),
    ('Iliana U. Garrison','Anne H. Reeves',NULL,'Abu Sayyaf Group'),
    ('Selma X. Petersen','Porter G. Raymond',NULL,'Boko Haram'),
    ('Sybil F. Macdonald','Branden R. Key',NULL,'Hizbul Mujahideen'),
    ('Gregory P. Salas','Alden U. Powers',NULL,'Abu Sayyaf Group'),
    ('Kay C. Mays','Ralph L. Ayala',NULL,'Al-Qaeda Kurdish Battalions'),
    ('Hedy B. Oneal','Quail Y. Frye',NULL,'Lashkar-e Tayyiba (Army of the Righteous)'),
    ('Ali F. Woodard','Baxter C. Burton',NULL,'al-Qa''ida'),
    ('Jason G. Petty','Nathan I. Brock',NULL,'Harakat ul-Mujahidin'),
    ('Nero E. Avery','Eagan J. Walls',NULL,'Palestine Liberation Front'),
    ('Jael L. Benson','Cora G. Huff',NULL,'Palestine Liberation Front'),
    ('Hilary G. Rice','Molly R. Hart',NULL,'Palestine Liberation Front'),
    ('Daquan I. Ryan','Melinda G. Dean',NULL,'Al-Qaeda Kurdish Battalions'),
    ('Troy Q. Cobb','Rhea H. Galloway',NULL,'Hizbul Mujahideen'),
    ('Allen R. Suarez','Aurelia O. Morton',NULL,'Boko Haram'),
    ('Herman I. Dixon','Tana B. Hardy',NULL,'Harakat ul-Mujahidin'),
    ('Zachery H. Witt','Marah R. Brewer',NULL,'Abu Sayyaf Group'),
    ('Camille O. Rocha','Myles Q. Barr',NULL,'Abu Sayyaf Group'),
    ('Idola B. Pitts','Bo T. Hubbard',NULL,'Abu Sayyaf Group'),
    ('Jacqueline Y. Hyde','Denise W. Gentry',NULL,'Harakat ul-Mujahidin'),
    ('Desirae N. Horton','Halee A. Burke',NULL,'Palestine Liberation Front'),
    ('Shafira B. Cobb','Ashely C. Barker',NULL,'Harakat ul-Mujahidin'),
    ('Reuben M. Holt','Scott V. Bolton',NULL,'al-Qa''ida'),
    ('Peter P. Stein','Dominique U. Haley',NULL,'Lashkar-e Tayyiba (Army of the Righteous)');
