CREATE TABLE IF NOT EXISTS terror_org (
    `city` VARCHAR(29) CHARACTER SET utf8,
    `organization_name` VARCHAR(41) CHARACTER SET utf8
);
INSERT INTO terror_org VALUES
    ('Silverton','Harakat ul-Mujahidin'),
    ('McCallum','Harakat ul-Mujahidin'),
    ('Emmen','Abu Sayyaf Group'),
    ('Plymouth','Harakat ul-Mujahidin'),
    ('Lagundo/Algund','Harakat ul-Mujahidin'),
    ('Bensheim','al-Qa''ida'),
    ('Parkland County','Abu Sayyaf Group'),
    ('Sulzano','Hizbul Mujahideen'),
    ('Rae-Edzo','Islamic Jihad Group'),
    ('Roermond','Al-Qaeda Kurdish Battalions'),
    ('Neufeld an der Leitha','Al-Qaeda Kurdish Battalions'),
    ('Musselburgh','Hizbul Mujahideen'),
    ('Ashbourne','Hizbul Mujahideen'),
    ('Southwell','Harakat ul-Mujahidin'),
    ('Asti','Islamic Jihad Group'),
    ('Puntarenas','Al-Qaeda Kurdish Battalions'),
    ('Morinville','Al-Qaeda Kurdish Battalions'),
    ('Roosendaal','Boko Haram'),
    ('Kirkcaldy','Boko Haram'),
    ('Pittsburgh','Abu Sayyaf Group'),
    ('Meugliano','Hizbul Mujahideen'),
    ('Lives-sur-Meuse','Abu Sayyaf Group'),
    ('Castanhal','Harakat ul-Mujahidin'),
    ('Gonnosnò','Lashkar-e Tayyiba (Army of the Righteous)'),
    ('Zwijnaarde','Lashkar-e Tayyiba (Army of the Righteous)'),
    ('Liernu','Islamic Jihad Union'),
    ('Aix-en-Provence','Harakat ul-Mujahidin'),
    ('Guelph','Palestine Liberation Front'),
    ('Gijón','Al-Qaeda Kurdish Battalions'),
    ('Roccanova','Lashkar-e Tayyiba (Army of the Righteous)'),
    ('Nelson','Al-Qaeda Kurdish Battalions'),
    ('Anjou','Abu Sayyaf Group'),
    ('Wigtown','Harakat ul-Mujahidin'),
    ('Bierk Bierghes','al-Qa''ida'),
    ('Schriek','Islamic Jihad Union'),
    ('Mjölby','Islamic Jihad Group'),
    ('Hamilton','Harakat ul-Mujahidin'),
    ('Millet','Harakat ul-Mujahidin'),
    ('Tacoma','Boko Haram'),
    ('Kansas City','Al-Qaeda Kurdish Battalions'),
    ('Kontich','Islamic Jihad Group'),
    ('Isola del Gran Sasso d''Italia','Boko Haram'),
    ('Wortel','Al-Qaeda Kurdish Battalions'),
    ('Frascati','Harakat ul-Mujahidin'),
    ('Ancaster Town','Hizbul Mujahideen'),
    ('Bathurst','Abu Sayyaf Group'),
    ('Kapuskasing','Boko Haram'),
    ('Sombreffe','Boko Haram'),
    ('Valley East','Harakat ul-Mujahidin'),
    ('Ronciglione','Boko Haram'),
    ('Pallavaram','Harakat ul-Mujahidin'),
    ('Largs','Harakat ul-Mujahidin'),
    ('Slijpe','Islamic Jihad Union'),
    ('Massa e Cozzile','Harakat ul-Mujahidin'),
    ('High Level','Palestine Liberation Front'),
    ('Port Hope','Al-Qaeda Kurdish Battalions'),
    ('Grave','Abu Sayyaf Group'),
    ('Thiaumont','Harakat ul-Mujahidin'),
    ('Ribnitz-Damgarten','Hizbul Mujahideen'),
    ('Osnabrück','Palestine Liberation Front'),
    ('Viggianello','Harakat ul-Mujahidin'),
    ('Gdynia','Boko Haram'),
    ('Palombaro','Lashkar-e Tayyiba (Army of the Righteous)'),
    ('Solre-Saint-Gry','Harakat ul-Mujahidin'),
    ('Goslar','Harakat ul-Mujahidin'),
    ('Oderzo','Abu Sayyaf Group'),
    ('Arnesano','Islamic Jihad Group'),
    ('Watson Lake','Boko Haram'),
    ('Lelystad','al-Qa''ida'),
    ('Santipur','Al-Qaeda Kurdish Battalions'),
    ('Saint-Denis-Bovesse','Al-Qaeda Kurdish Battalions'),
    ('Águas Lindas de Goiás','Boko Haram'),
    ('Petrópolis','Hizbul Mujahideen'),
    ('Calgary','Boko Haram'),
    ('Baranello','Palestine Liberation Front'),
    ('Glovertown','Islamic Jihad Group'),
    ('Oberwart','Harakat ul-Mujahidin'),
    ('Kirkby Lonsdale','Abu Sayyaf Group'),
    ('Vaux-sur-Sure','Boko Haram'),
    ('Westrem','Hizbul Mujahideen'),
    ('Colobraro','Abu Sayyaf Group'),
    ('Soma','Al-Qaeda Kurdish Battalions'),
    ('Patalillo','Lashkar-e Tayyiba (Army of the Righteous)'),
    ('West Vancouver','al-Qa''ida'),
    ('Weymouth','Harakat ul-Mujahidin'),
    ('Pergola','Palestine Liberation Front'),
    ('Tropea','Palestine Liberation Front'),
    ('Ketchikan','Palestine Liberation Front'),
    ('Bettiah','Al-Qaeda Kurdish Battalions'),
    ('Sovizzo','Hizbul Mujahideen'),
    ('Onitsha','Boko Haram'),
    ('Tresigallo','Harakat ul-Mujahidin'),
    ('Bergeggi','Abu Sayyaf Group'),
    ('La Cisterna','Abu Sayyaf Group'),
    ('Santa Cesarea Terme','Abu Sayyaf Group'),
    ('Paulatuk','Harakat ul-Mujahidin'),
    ('Seraing','Palestine Liberation Front'),
    ('Placanica','Harakat ul-Mujahidin'),
    ('Gijón','al-Qa''ida'),
    ('Avadi','Lashkar-e Tayyiba (Army of the Righteous)');
